### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by PeterGillham** [codecadwallader/codemaid#146]
Ooops this has already been covered, sorry.
Hope this helps :-1: 
 [CodeMaid Handled Exception 12:41:24 PM] Stopped cleaning Mycode.cs': System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.TextDocument.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.RemoveWhitespaceLogic.RemoveEOLWhitespace(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__1()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)
[CodeMaid Handled Exception 12:42:56 PM] Stopped cleaning Mycode2.cs': System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.EditPoint.FindPattern(String Pattern, Int32 vsFindOptionsValue, EditPoint& EndPoint, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UpdateLogic.UpdateEndRegionDirectives(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__1()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Yep, this call stack shows the same internal VS library as #83.  Unfortunately we don't currently have a solution as it appears to be leaks within Visual Studio.. or we are using the APIs incorrectly.
