### ISSUE TITLE
Spade window is empty for C# file

### ISSUE THREAD

**Issue by bobsgame** [codecadwallader/codemaid#183]
Using VS 2015 Community, CodeMaid version 0.9.0

Attempts to load (says loading) and then disappears and leaves this error:
```
[CodeMaid Handled Exception 01:57:26 PM] Unable to build code model for 'C:\Users\Administrator\Documents\game\Assets\game\Scripts\Gameplay\game.cs': System.NullReferenceException: Object reference not set to an instance of an object.
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsRecursively(SetCodeItems codeItems, CodeElement codeElement)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
```

Additionally, switching to a different file gave this error:
```
[CodeMaid Handled Exception 02:01:11 PM] Unable to build code model for 'c:\users\administrator\documents\game\assets\game\scripts\gameplay\settings.cs': System.Runtime.InteropServices.COMException (0x8002801D): Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
   at EnvDTE.CodeElement.get_Children()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsRecursively(SetCodeItems codeItems, CodeElement codeElement)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
```

Also, I'd like to request to cache the file so it doesn't have to be reparsed every time.  I'm working with some long classes and it takes maybe 5+ seconds to parse.  Also having it remember collapsed regions (in sort by type) in the Spade window when switching between files so I don't need to collapse the fields sections every time, or an option to hide fields, like the Outline View in Eclipse.

I'll look into patching this myself.

**Comment by bobsgame** [comment]
This appears to be due to having another 3rd party extension with similar functionality installed and enabled, VS10x CodeMAP.
