### ISSUE TITLE
Remove unused usings throwing COMException

### ISSUE THREAD

**Issue by Clockwork-Muse** [codecadwallader/codemaid#187]
Removing unused using statements is failing with the following stack trace:

>[CodeMaid Handled Exception 05:03:46 PM] Stopped cleaning 'TaskRtTests.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.RemoveUnusedUsingStatements(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

...using VS Community edition.

Now, this is only occurring on corefx projects, so I'm assuming it's something related to that.  Sorting the statements works just fine.

**Comment by codecadwallader** [comment]
If you invoke the remove unused using statements command directly on a CoreFX project, does the same error occur?

**Comment by Clockwork-Muse** [comment]
@codecadwallader - running either `CodeMaid.CleanupOpenCode` or `CodeMaid.CleanupCode` from the command window produces an identical/similar error:

>[CodeMaid Handled Exception 11:58:51 AM] Stopped cleaning 'taskrttests.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.RemoveUnusedUsingStatements(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

I didn't see a command for just removing unused usings.

**Comment by codecadwallader** [comment]
Part of CodeMaid's cleanup is to invoke native Visual Studio commands, such as sorting and removing using statements.  The Visual Studio command to remove unused using statements is `Edit.RemoveUnusedUsings`.  Can you try invoking that directly from the command window with one of the CoreFX files open?  The same command can be invoked through the Edit->IntelliSense->Remove Unnecessary Usings or through right clicking inside the editor window.

**Comment by Clockwork-Muse** [comment]
Attempting to run it yields `Command "Edit.RemoveUnusedUsings" is not available.`, even though it shows up in auto-complete.  It doesn't appear in the tool bar or the right click menus (only "sort usings")..... hmm.  
The command does appear in other project types, just not corefx.  Will be bugging them too, probably.

**Comment by codecadwallader** [comment]
The command always exists (which is why auto-complete still finds it) but it may not always be available to use.  Since it is explicitly not in the tool bar or right click menus, it sounds like something they probably deliberately have not enabled yet.  I'd recommend opening an issue with them for more information: https://github.com/dotnet/corefx/issues

**Comment by codecadwallader** [comment]
Closing due to inactivity and as this seems like an issue with CoreFX.
