### ISSUE TITLE
Spade doesn't work with ASP.NET Core projects in VS2017RC.

### ISSUE THREAD

**Issue by HTD** [codecadwallader/codemaid#383]
### Environment
- Visual Studio version: 2017RC Enterprise
- CodeMaid version: 10.2
- Code language: C#

### Description
On first load I see empty regions, after refresh the view is empty.

### Steps to recreate
1. Create new ASP.NET Core project.
2. Open any C# file.
3. Open Spade view.

### Current behavior
Empty spade view.

### Expected behavior
Actual code items view.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I do not currently have the core templates installed.  A few things to check:

1.  If you enable diagnostics mode (CodeMaid->Options->General->"Diagnostics mode"), repeat your steps and check the Output tool window.. what do you see?
2.  If you create another kind of project (e.g. C# class library), does it work as expected on your machine?
3.  If you run cleanup on the C# file, does it work as expected?  Under the covers the same code model is used for visualization (Spade), cleaning and reorganizing.

**Comment by HTD** [comment]
ad 1: Here's what I got:

```
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsStale changing to 'True' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelCache.StaleCodeModel in cache for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.RetrieveAllCodeItemsAsync for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelCache.GetCodeModel for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM]   --retrieved from cache (stale).
[CodeMaid Diagnostic 02:14:21 PM] CodeModelCache.StaleCodeModel in cache for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.RetrieveAllCodeItemsAsync for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelCache.GetCodeModel for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM]   --retrieved from cache (stale).
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.BuildCodeItems started for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.BuildCodeItems started for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsBuilding changing to 'True' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsBuilding changing to 'True' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsStale changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsStale changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] Unable to build code model for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs': System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IMutableComWrapperFixed'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{3F2A41D1-125C-49C1-9773-1E0ECD311F00}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.PlatformUI.ComWrapperFactory.CreateAggregatedObject(Object obj)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Interop.ApartmentSensitiveComObject.GetComHandle[THandle,TObject]()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelProjectCache.GetOrCreateFileCodeModel(String filePath, Object parent)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectCodeModel.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSCodeModelFactory.GetFileCodeModel(IWorkspaceProjectContext context, ProjectItem item)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ProjectContextCodeModelProvider.GetFileCodeModel(ProjectItem fileItem)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem.get_FileCodeModel()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveFileCodeModel(ProjectItem projectItem)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 02:14:21 PM] Unable to build code model for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs': System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IMutableComWrapperFixed'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{3F2A41D1-125C-49C1-9773-1E0ECD311F00}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.PlatformUI.ComWrapperFactory.CreateAggregatedObject(Object obj)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Interop.ApartmentSensitiveComObject.GetComHandle[THandle,TObject]()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelProjectCache.GetOrCreateFileCodeModel(String filePath, Object parent)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectCodeModel.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSCodeModelFactory.GetFileCodeModel(IWorkspaceProjectContext context, ProjectItem item)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ProjectContextCodeModelProvider.GetFileCodeModel(ProjectItem fileItem)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem.get_FileCodeModel()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveFileCodeModel(ProjectItem projectItem)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsBuilding changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModel.IsBuilding changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.LoadLazyInitializedValues for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.LoadLazyInitializedValues for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.CodeModelBuilt raised for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:21 PM] CodeModelManager.CodeModelBuilt raised for 'C:\Source\Lab\DotNetCore\WoofCms\Startup.cs'
[CodeMaid Diagnostic 02:14:34 PM] WindowEventListener.OnWindowChange raised for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModelManager.RetrieveAllCodeItemsAsync for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModelCache.GetCodeModel for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM]   --retrieved from cache (stale).
[CodeMaid Diagnostic 02:14:34 PM] CodeModelManager.BuildCodeItems started for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModel.IsBuilding changing to 'True' for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModel.IsStale changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] Unable to build code model for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs': System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IMutableComWrapperFixed'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{3F2A41D1-125C-49C1-9773-1E0ECD311F00}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.PlatformUI.ComWrapperFactory.CreateAggregatedObject(Object obj)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Interop.ApartmentSensitiveComObject.GetComHandle[THandle,TObject]()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelProjectCache.GetOrCreateFileCodeModel(String filePath, Object parent)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectCodeModel.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProject.GetFileCodeModel(ProjectItem item)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSCodeModelFactory.GetFileCodeModel(IWorkspaceProjectContext context, ProjectItem item)
   at Microsoft.VisualStudio.ProjectSystem.VS.LanguageServices.ProjectContextCodeModelProvider.GetFileCodeModel(ProjectItem fileItem)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem.get_FileCodeModel()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveFileCodeModel(ProjectItem projectItem)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 02:14:34 PM] CodeModel.IsBuilding changing to 'False' for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModelManager.LoadLazyInitializedValues for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'
[CodeMaid Diagnostic 02:14:34 PM] CodeModelManager.CodeModelBuilt raised for 'C:\Source\Lab\DotNetCore\WoofCms\Backend\DB.cs'

```

ad 2: Yes, I just opened my WPF project, Spade works as charm.

ad 3: I used cleanup on all opened files (about 10 files), I was afraid to use it on project because I had some uncommitted changes. It seems like files were cleaned up correctly, all became modified, but if it worked in 100%? IDK, because the files were already formatted with VS options. 

A hint: ASP.NET Core projects do not use traditional project file. The project file doesn't decide which files are included or excluded from the project. There is no option to exclude a file. All in project directory are included. However I'm not sure if all these files are added to source control. Generated JS files (compiled from TS) don't have (+) markers.

I use also Supercharger extension (as trial) and it displays its code view properly. Of course I tested CodeMaid Spade without Supercharger installed. Then I retested them side-by-side. Spade does not work with Core projects, works with Windows Application projects.

If it's relevant, my machine runs Windows 10 (14393.576), x64, system installed less than a month ago. It was reinstalled due to issues with Visual Studio. On previous installation I tested CodeMaid Spade with Visual Studio 15 beta. I noticed identical behavior. The reason I use early versions of VS is mainly Core having the most changes from 2015.

**Comment by codecadwallader** [comment]
Thank you for all of the diagnostic information.  It sounds like the FileCodeModel API may not be available for ASP.NET Core projects.  Some cleanup actions may still run, but only those that do not require the FileCodeModel (e.g. regular expression based changes).

ASP.NET Core projects may only support the newer Roslyn API.  We need to do a large rewrite in order to support that API, see #251 

So unfortunately there's probably no quick fix until that rewrite occurs.  Help is absolutely welcome.

**Comment by HTD** [comment]
I wish I had time to help with the code at this very moment, but I surely can help with testing anytime, since I code a lot using various project types (Core, WPF, WinForms, UWP).

**Comment by HTD** [comment]
After latest update to Visual Studio 2017 RC Spade works properly in .NET Core projects.
It seems like it was a bug in Visual Studio, not Spade.

**Comment by codecadwallader** [comment]
Awesome!  I didn't expect it would work for those projects.
