### ISSUE TITLE
Canceling cleanup selected code results in "Unknown hard error" VS crash

### ISSUE THREAD

**Issue by nnpcYvIVl** [codecadwallader/codemaid#402]
### Environment
- Visual Studio version: 2017 RC Community latest version
- CodeMaid version: 10.2.7
- Code language: C#

### Description
Canceling cleanup selected code results in "Unknown hard error" VS crash

### Steps to recreate
1. Open VS and solution
2. Right click on large (1MB) file in solution explorer and select Cleanup selected code
3. When cleanup progress dialog appears click cancel

### Current behavior
Cleanup progress dialog never cancels and stays on screen until VS eventually crashes with "Unknown hard error"

### Expected behavior
It shouldn't crash and the cancel dialog should be more responsive.

**Comment by nnpcYvIVl** [comment]
Following the same steps on a smaller file (600KB) doesn't crash with "Unknown hard error" but fails with the following exception.

[CodeMaid Handled Exception 01:25:37 PM] CodeMaid Cleanup for 'test library.cs' was stopped: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.EditPoint.FindPattern(String Pattern, Int32 vsFindOptionsValue, EditPoint& EndPoint, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.CodeElementHelper.GetFieldDeclaration(CodeVariable codeField)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.InsertExplicitAccessModifierLogic.InsertExplicitAccessModifiersOnFields(IEnumerable`1 fields)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.

When you open up the cleanup progress dialog via Solution Explorer it is generally intended for scenarios where you are cleaning a large number of files (e.g. an entire project).  The progress dialog will allow you to stop cleanup between files, but will not abort in the middle of an individual file.  So in your scenario where you are cleaning a single file, clicking Cancel would not have any real effect.

If you invoke cleanup via the keyboard shortcut, CodeMaid menu or document context menu.. what behavior do you see?

For the secondary scenario.. in general if you are out of memory then most CodeMaid operations will not work correctly.  I would recommend restarting Visual Studio before retesting these issues and confirming you have sufficient memory on your system.

Hope it helps.

**Comment by nnpcYvIVl** [comment]
My system has 16GB of RAM with lots free. It fails even when I close and reopen Visual Studio and run cleanup before trying anything else.

When I run 'Cleanup Active Document' from the main menu I get this or the previously mentioned VS crash with "Unknown hard error".

[CodeMaid Handled Exception 11:43:36 AM] CodeMaid Cleanup for 'library.cs' was stopped: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.EditPoint.FindPattern(String Pattern, Int32 vsFindOptionsValue, EditPoint& EndPoint, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.InsertExplicitAccessModifierLogic.InsertExplicitAccessModifiersOnMethods(IEnumerable`1 methods)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Ok, some further things to try:

1)  Before you start cleanup, how much RAM is Visual Studio consuming?
2)  As you run cleanup and monitor your RAM, how much is Visual Studio increasing up towards before the OutOfMemoryException occurs?
3)  How large is the solution you're loading and the file you are trying to clean?
4)  Do you see the same behavior if you create a new solution and project (e.g. Console App) and run cleanup against that?

**Comment by nnpcYvIVl** [comment]
1. 215 MB.
2. 3 GB.
3. 400 files, 6 MB. So far I have only tried to run the cleanup on 2 files (1MB and 600 KB) in the solution.
4. No, running cleanup on a new solution runs and completes successfully.

**Comment by codecadwallader** [comment]
Ok, those sound like pretty large files you're trying to process.  I've tested up to ~10,000 lines successfully.  How many lines are they?  In the same solution, do smaller files clean up successfully?

**Comment by nnpcYvIVl** [comment]
Of the two so far that crash VS, one is 6000 and one is 20000 lines.

Other files in the solution cleanup fine.

**Comment by codecadwallader** [comment]
The complexity of the file can be a factor on how much memory is consumed as well.

Please see #209 for some information about memory issues.  If you would like to attach your files to this issue as an example you may do so but I assume they're proprietary.

**Comment by nnpcYvIVl** [comment]
The referenced code files are proprietary and can't be posted.

In their place I have attached a simple "memory stress test" file that causes an Unknown Hard Error every time I try to clean it.

[CodeMaidTest.zip](https://github.com/codecadwallader/codemaid/files/804510/CodeMaidTest.zip)
