### ISSUE TITLE
Incorrect Class order after using Reorganize Active Document

### ISSUE THREAD

**Issue by stoned1999** [codecadwallader/codemaid#424]
### Environment
- Visual Studio: 2017 Enterprise
- CodeMaid version: 10.3
- Code language: VB.NET

### Description
Reorganize incorrectly moves non form class above form class in file. 

For good or bad I have a Class file that contains a Form Class and another utility class they were originally arranged as form then utility class.

Public Class UFCWTaskManager
    Inherits System.Windows.Forms.Form
End Class

Public Class CrossThreadDelegate
...
End Class

After running the Reorganize Active Document feature the Utility Class is placed ahead of the Form Class causing the program to fail initialization

### Steps to recreate
1. Apply Reorganize to Form Class
2. Save
3. Run

### Current behavior
Class order is changed to

Public Class CrossThreadDelegate
...
End Class

Public Class UFCWTaskManager
    Inherits System.Windows.Forms.Form
End Class

Resulting in this error

System.Resources.MissingManifestResourceException occurred
  HResult=0x80131532
  Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "UFCW.UFCWTaskManager.resources" was correctly embedded or linked into assembly "UFCW.UFCWTaskManager" at compile time, or that all the satellite assemblies required are loadable and fully signed.
  Source=mscorlib
  StackTrace:
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at UFCW.UFCWTaskManager.InitializeComponent() in C:\VB.NET.2017\UFCWTaskManager\UFCWTaskManager\Main.vb:line 345

### Expected behavior
Form Class should be placed ahead of other classes.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I'm not very familiar with VB, can you provide any links (e.g. MSDN) that point to the rules for when/how class order is restricted?

We do have some exceptions in reorganizing for known cases where layout order matters.  This is usually already indicated by an attribute decoration (e.g. [StructLayout]).  https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/CodeReorganizationManager.cs#L206

There's a couple obvious workarounds in the meantime such as skipping that file for reorganization or splitting the classes into separate files.

**Comment by stoned1999** [comment]
This KB article exists

https://support.microsoft.com/en-us/help/318603/you-may-receive-a-system.resources.missingmanifestresourceexception-error-message-when-you-access-the-.resources-file-of-the-form-at-run-time

**Comment by codecadwallader** [comment]
Thanks for the link.  What is the extension for the file that is exhibiting the issue?  As an example we ignore .Designer.vb files by default from reorganization because they are largely auto-generated content.

**Comment by stoned1999** [comment]
The class file ends as .VB, it has an associated file that ends in .resx

**Comment by stoned1999** [comment]
The form class that should be first would be the class inheriting from System.Windows.Forms.Form

Public Class UFCWTaskManager
    Inherits System.Windows.Forms.Form
