### ISSUE TITLE
Empty Spade in .Net Core projects with VS2017

### ISSUE THREAD

**Issue by duckblaster** [codecadwallader/codemaid#462]
### Environment
- Visual Studio version: 2017 Preview (15.3.0 Preview 3.0)
- CodeMaid version: 10.4.53
- Code language: C3

### Description
Spade is empty (event after a refresh) on the following project types:
ASP.Net Core on Full Framework
Asp.Net Core on .Net Core
Console App on .Net Core
Possibly related to #383? different log messages though

### Steps to recreate
1. Create new project
2. Open *.cs file from project
3. Open Spade

### Current behavior
Empty spade, even after refresh, log below with diagnostics on
```
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.RetrieveAllCodeItemsAsync for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelCache.GetCodeModel for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsStale changing to 'True' for ''
[CodeMaid Diagnostic 04:25:09 PM]   --added to cache (stale).
[CodeMaid Diagnostic 04:25:09 PM] CodeModelCache.StaleCodeModel in cache for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.RetrieveAllCodeItemsAsync for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelCache.GetCodeModel for ''
[CodeMaid Diagnostic 04:25:09 PM]   --retrieved from cache (stale).
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.BuildCodeItems started for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.BuildCodeItems started for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsBuilding changing to 'True' for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsBuilding changing to 'True' for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsStale changing to 'False' for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsStale changing to 'False' for ''
[CodeMaid Diagnostic 04:25:09 PM] Unable to build code model for '': System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Document.get_ProjectItem()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 04:25:09 PM] Unable to build code model for '': System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Document.get_ProjectItem()
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsBuilding changing to 'False' for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModel.IsBuilding changing to 'False' for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.LoadLazyInitializedValues for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.LoadLazyInitializedValues for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.CodeModelBuilt raised for ''
[CodeMaid Diagnostic 04:25:09 PM] CodeModelManager.CodeModelBuilt raised for ''
```

### Expected behavior
Actual code items view.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, and for finding the previous occasion where there was an issue with Spade and Core.  A lot of those comments still apply, such as I'm not sure if .NET Core projects will continue to work with the FileCodeModel API we utilize.

In the log messages above, the empty quote is where a file path would typically be shown.  Here's a few things to try:

1.  If you repeat the same action on a non-Core project, does it work as expected and show the file name in the diagnostics above as expected?

2.  If you close Spade, close and reopen a Core file, then invoke a cleanup are the diagnostics the same as above or different?  Under the covers Cleaning/Digging rely on the same CodeModel building process.  Spade will usually trigger the building first if its open.  By closing Spade and closing the file any cached model should(tm) be released.  By opening the file and invoking a cleanup a new CodeModel will attempt to build.  I would generally expect the behavior to be the same, but this could point out any potential delayed loading effects.

3.  If you right click on a Core file and invoke a CodeMaid cleanup, does it run and/or are the diagnostic logs the same?  There's a possibility that the FileCodeModel is fine and its an issue with the Solution Explorer / Project Item APIs since you're not seeing a path in the logs.

**Comment by duckblaster** [comment]
A normal console app on full framework works as expected.
Cleanup works for current/all files and spade loads normally afterwards for that file(s)
When loading project today I got this in the log (before running cleanup)
```
[CodeMaid Diagnostic 08:30:28 AM] CodeModel.IsStale changing to 'True' for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM] CodeModelCache.StaleCodeModel in cache for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM] CodeModelManager.RetrieveAllCodeItemsAsync for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM] CodeModelCache.GetCodeModel for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM]   --retrieved from cache (stale).
[CodeMaid Diagnostic 08:30:28 AM] CodeModelManager.BuildCodeItems started for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM] CodeModel.IsBuilding changing to 'True' for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:28 AM] CodeModel.IsStale changing to 'False' for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:29 AM] Unable to build code model for 'C:\Path\File.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider, String filePath, IVisualStudioHostProject projectOpt, Boolean needsSave, Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.TextManagerAdapter.CreateTextPoint(FileCodeModel fileCodeModel, VirtualTreePoint point)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.GetStartPoint(vsCMPart part)
   at EnvDTE.CodeElement.GetStartPoint(vsCMPart Part)
   at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemUsingStatement.RefreshCachedPositionAndName()
   at SteveCadwallader.CodeMaid.Model.CodeItems.FactoryCodeItems.CreateCodeItemElement(CodeElement codeElement)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsRecursively(SetCodeItems codeItems, CodeElement codeElement)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Diagnostic 08:30:29 AM] CodeModel.IsBuilding changing to 'False' for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:29 AM] CodeModelManager.LoadLazyInitializedValues for 'C:\Path\File.cs'
[CodeMaid Diagnostic 08:30:29 AM] CodeModelManager.CodeModelBuilt raised for 'C:\Path\File.cs'
```

**Comment by duckblaster** [comment]
Closing and reopening a file I need to rerun cleanup to get it to show in spade again

**Comment by codecadwallader** [comment]
Thanks for the information.  That's a bit unexpected, but it sounds like somehow the file is not ready for processing immediately yet works fine if you defer the building of the code model.  I know there have been a number of advances in Visual Studio to delay loading projects in solution explorer.  This behavior makes me think that perhaps they did something similar in-editor to delay loading elements.  That's a stretch of imagination though and I haven't heard anything along those lines.

Another thing you can try, is the explicit refresh button in the top left corner of the Spade toolbar.  This will cause the code model to be marked as stale and explicitly regenerated.  If you click that button after the code model fails to build does it consistently fail to build or does it work after some period of time?
