### ISSUE TITLE
Exception when executing on .cs file with C++CLI code

### ISSUE THREAD

**Issue by TobiasKnauss** [codecadwallader/codemaid#463]
### Environment
- Visual Studio version: [2015 Pro]
- CodeMaid version: [10.4.53]
- Code language: [C#, C++/CLI]

### Description
I am currently converting C++/CLI code into C#. I copy the C++/CLI code into a .cs file and convert it step-by-step. When saving files that still have C++/CLI code, there are exceptions in CodeMaid:
```
[CodeMaid Handled Exception 10:57:00 ] CodeMaid Cleanup for 'CArray.cs' was stopped: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.LookupNode(SyntaxNodeKey nodeKey, SyntaxTree syntaxTree)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractKeyedCodeElement.LookupNode()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.<>c__DisplayClass36_0.<GetStartPoint>b__0()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.GetStartPoint(vsCMPart part)
   at EnvDTE.CodeElement.GetStartPoint(vsCMPart Part)
   at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.get_StartPoint()
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UpdateLogic.<>c.<UpdateSingleLineMethods>b__7_0(CodeItemMethod x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UpdateLogic.UpdateSingleLineMethods(IEnumerable`1 methods)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)
```

Sample code:
```
  generic<private class T>
  static array<T>^  FromString (String^ i_sPrefix,
                                String^ i_sValues,
                                String^ i_sSuffix,
                                String^ i_sSeparator)
    {
      T[] aValue = new T[0];
      aValue = (T[])CIList.FromString<T> (i_sPrefix, i_sValues, i_sSuffix, i_sSeparator, aValue);
      return aValue;
    }
```
Also, it inserts "private" before the function name, but misses the space, making it "privateFromString".

### Steps to recreate
insert code into .cs, execute cleanup.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  If you have invalid code, it is possible for it to be interpreted incorrectly.  I'd recommend you disable cleanup on save when deliberately saving invalid files so CodeMaid doesn't kick in at that time.
