### ISSUE TITLE
Exception thrown during cleanup

### ISSUE THREAD

**Issue by KeksImperium** [codecadwallader/codemaid#526]
### Environment
- Visual Studio version: 15.5.6
- CodeMaid version: 10.4
- Code language: VB

### Description
Two exceptions are thrown when i try to perform Cleanup Active Document:

> [CodeMaid Handled Exception 08:52:54 ] TryDefault caught an exception on 'System.Func`1[System.Boolean]': System.Runtime.InteropServices.COMException (0x8000FFFF): Schwerwiegender Fehler (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEUnexpected()
>    at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.GetFunctionKind(IMethodSymbol symbol)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeFunction.get_FunctionKind()
>    at EnvDTE80.CodeFunction2.get_FunctionKind()
>    at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemMethod.<.ctor>b__6_4()
>    at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.TryDefault[T](Func`1 func)
> [CodeMaid Handled Exception 08:52:54 ] TryDefault caught an exception on 'System.Func`1[System.Boolean]': System.Runtime.InteropServices.COMException (0x8000FFFF): Schwerwiegender Fehler (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEUnexpected()
>    at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.GetFunctionKind(IMethodSymbol symbol)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeFunction.get_FunctionKind()
>    at EnvDTE80.CodeFunction2.get_FunctionKind()
>    at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemMethod.<.ctor>b__6_5()
>    at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.TryDefault[T](Func`1 func)

The .vb file has > 2000 lines of code.
Smaler files work just fine...

### Steps to recreate
1. Open "large" .vb file
2. Click "Cleanup Active Document"

### Current behavior
Exceptions is thrown and no cleanup happend :(

### Expected behavior
No exception and clean file

**Comment by codecadwallader** [comment]
The error message looks like a specific problem with one of the method definitions within the file that is causing the error.  Can you either:

1.  Provide a minimal solution that includes that file.
2.  If you don't want to share the file (understandable), then narrow down to the code segment that is causing the issue.  A good way to do this would be remove half the file content, see if the issue still happens.  Whenever it does, continue by removing another half.  Whenever it does not, reverse the change and remove the other half.  Rinse and repeat until you get down to the relevant code that is causing the error.

**Comment by KeksImperium** [comment]
This Method is causing the error:

`Public Shared Widening Operator CType(auftrag As AuftragObject) As Vorbeschaeftigung
            Dim result = New Vorbeschaeftigung
            result.VertragId = auftrag.VertragID
            result.Id = -1
            result.IstVorbeschaeftigung = True
            result.KDID = auftrag.KDID
            result.KID = auftrag.KID
            result.MAID = auftrag.MAID
            ' Auftragsende muss bei alten Aufträgen nicht unbedingt befüllt sein
            Dim ende = If(auftrag.Vertragsende.HasValue, auftrag.Vertragsende, auftrag.MaxVertragsende)
            result.Zeitraum = New DateRange(auftrag.Vertragsbeginn.GetValueOrDefault(), ende.GetValueOrDefault())

            Return result
        End Operator
`

**Comment by codecadwallader** [comment]
Thanks for providing the method.  I'm not familiar with overriding operators in VB so when I just drop it into a console project it isn't valid.  Can you provide a minimal solution that includes this method?
