### ISSUE TITLE
out-of-memory Exception

### ISSUE THREAD

**Issue by TobiasKnauss** [codecadwallader/codemaid#533]
### Environment
- Visual Studio 2015 Pro, v.14.0.25431.01 Update 3
- CodeMaid 10.4.53
- C#
- Win 7 Pro x64 SP1, all Windows Updates installed.

### Description
When saving a certain .cs file, the RAM usage of VS increases by about 100-150MB at each saving operation. Chances are high that CodeMaid is responsible for that, because when about 2.8GB is reached, CodeMaid crashes with out-of-memory-exception.

### Steps to recreate
None, that I know.

### Current behavior
obviously a memory leak or resources that are not freed.

### Expected behavior
Please fix the bug. But as I can imagine that this is quite impossible without more details, please add more logging for further diagnosis. Current Diagnostics mode does not provide any useful info (just 7 lines):

[CodeMaid Diagnostic 01:23:58 ] RunningDocumentTableEventListener.BeforeSave raised for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'
[CodeMaid Diagnostic 01:23:58 ] CodeCleanupManager.Cleanup started for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'
[CodeMaid Diagnostic 01:23:58 ] CodeModelManager.RetrieveAllCodeItems for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'
[CodeMaid Diagnostic 01:23:58 ] CodeModelCache.GetCodeModel for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'
[CodeMaid Diagnostic 01:23:58 ]   --retrieved from cache (not stale).
[CodeMaid Diagnostic 01:23:59 ] CodeCleanupManager.Cleanup completed for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'
[CodeMaid Diagnostic 01:23:59 ] RunningDocumentTableEventListener.AfterSave raised for 'D:\sw_development\swcore\pcbi\CEasyLogixPCBI.cs'

**Comment by codecadwallader** [comment]
See #209 for more details.  There is a linear relationship between the size of the file and how much memory is required, and known issues with how Visual Studio releases memory over time.

**Comment by TobiasKnauss** [comment]
Please reopen. The linked issue does not match my situation. My solution is much smaller and I never had problems with CodeMaid until I converted that solution from C++CLI to C#.

**Comment by codecadwallader** [comment]
Ok, but keep in mind that it is still likely to be very linked to the same underlying cause.  Visual Studio natively leaks memory the more operations that are run through it so its probably highly contingent on the size of the file.  If you are feeding a massive file through, it may run out of memory.

**Comment by TobiasKnauss** [comment]
I just tested with CodeMaid enabled and disabled. The test was "saving a large cs file (about 30k lines).
After opening the solution in VS 2015, the RAM usage was at about 200MB. With CodeMaid disabled ("Automatic Cleanup on Save - OFF), it remained at these 200MB at every saving operation, and also when calling "format document".
With CodeMaid enabled, the RAM consumption raised to 800MB after the 1st save, then 1400MB, 1800MB. So there seems to be a pretty severy memory issue inside your tool.
I will support on debugging if possible, but you need to tell me what to test.

**Comment by codecadwallader** [comment]
Thank you for being willing to pitch in.  If you would like to run some memory analysis to find what kinds of objects are leaking, that would be the most useful.

A few years ago we did a similar study and found that it was an underlying SDK class in Visual Studio that was leaking.  The difference from the test you ran is that you're not utilizing Visual Studio's SDK to access APIs.  When CodeMaid runs, it is going to invoke Visual Studio APIs in order to do its own processing.  It was objects within the Visual Studio API that were leaking (as opposed to CodeMaid leaking).  Since those underlying APIs were where we saw a leak there wasn't much we could do about it other than not use their APIs.  Please take a look at #83 for more details.

Things certainly could have changed over the years, but I suspect that issue is still the root of growth for large files since it was never resolved.  Those APIs are no longer being maintained either so I don't expect them to have been fixed or that they will be fixed.

As mentioned on that other issue, a rewrite to Roslyn could let us bypass those issues.. but it's a very massive rewrite.

**Comment by TobiasKnauss** [comment]
>  If you would like to run some memory analysis to find what kinds of objects are leaking, that would be the most useful.
You need to give me some more details what to test and how. Do I have to download your code and compile it and run it in VS debugger while another VS is using it and running my own solution or what? I don't know which info you need, so please provide some instructions.

**Comment by TobiasKnauss** [comment]
Here's an exception that is raised when RAM usage is at 2.8GB (actually I have 16GB of RAM installed, but VS is a 32bit application):

[CodeMaid Handled Exception 12:46:44 ] CodeMaid Cleanup for 'frmmain.cs' was stopped: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.TextDocument.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.RemoveWhitespaceLogic.RemoveEOLWhitespace(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Ok, thanks for running the test.  That is the same call stack we saw in #83 so it looks like things have not changed.

**Comment by TobiasKnauss** [comment]
Can you work around it? Currently I need to restart VS about once in an hour. But only if CodeMaid is active; if disable, then there is no "memory leak".
It's sad that MS hasn't fixed that bug that you obviously trigger using the VS API, but it's still your app that causes the bug to appear.
