### ISSUE TITLE
Cannot reorganize document on Visual Studio 2017 15.7 Preview 4

### ISSUE THREAD

**Issue by eliashdezr** [codecadwallader/codemaid#543]
### Environment
- Visual Studio version: Visual Studio 2017 15.7 Preview 4
- CodeMaid version: v10.4.53
- Code language: C#

### Description
After updated to the latest version of Visual Studio

### Steps to recreate
1. Open VS
2. Open any .cs file 
3. Select "Reorganize Active Document" from the CodeMaid menu

### Current behavior
Get this message
![image](https://user-images.githubusercontent.com/6153607/39009585-a9827d16-43d1-11e8-9f7b-9828413effc7.png)

Cleanup is working tho.

I tried reinstalling CodeMaid but didn't solve the problem.

**Comment by eliashdezr** [comment]
Quick update. Tried the steps from here: https://github.com/codecadwallader/codemaid/issues/382

But it doesn't solve the issue, here's what the diagnostic window says when running `Reorganize > Clean > Reorganize`
[codemaid_debug.txt](https://github.com/codecadwallader/codemaid/files/1929687/codemaid_debug.txt)

Also, the Spade section is empty:
![image](https://user-images.githubusercontent.com/6153607/39016816-35654646-43e7-11e8-88b0-79b2f6d9c076.png)

**Comment by vsuchan** [comment]
I confirm the error in Visual Studio Preview 15.7 preview 4. Log for this Error:

[CodeMaid Handled Exception 10:57:04 dop.] CodeMaid Cleanup for 'AddressConfiguration.cs' was stopped: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.TextDocument.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.RemoveWhitespaceLogic.RemoveEOLWhitespace(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I am unable to reproduce the issue with Visual Studio 15.6.6 (latest non-preview version).  It looks like the two call stacks start off from different parts of CodeMaid but both end up down in the VsRegexFinder within the Visual Studio API.  Can you confirm if the issue doesn't exist for you in the non-preview version?  That would hint that perhaps the API was changed with the latest preview version.

**Comment by vsuchan** [comment]
Yes it's correct. This problem is only in Visual Studio 2017 Preview version 15.7.0 Preview 4. Earlier version is fine. Problem is independent on computer. I see it on two different computers.

**Comment by eliashdezr** [comment]
v15.7.0 Preview 2 is working fine.

**Comment by codecadwallader** [comment]
Yikes, thank you for the additional detail.  

Similar to #544 it looks like there has been a significant change to the VsRegexFinder class within the Visual Studio API with Preview 4 that is creating a lot of issues.  If you could report this issue to Microsoft, it would be greatly appreciated (quantity of reports matters for their prioritization).

**Comment by heku** [comment]
This should be due to the VS issue which I had reported to the VS team.
https://developercommunity.visualstudio.com/content/problem/237005/find-and-replace-by-regular-throw-object-reference.html

**Comment by BabyToy** [comment]
Also having this issue on VS15.7.0.

However Codemaid runs fine on a VS2015 version. Both are using the same 10.4.53 Codemaid.

**Comment by codecadwallader** [comment]
Fantastic - thanks for reporting it and confirming it was an issue directly in their regular expression API!

**Comment by willemduncan** [comment]
Hello @heku, in the issue you reported on the Developer Community, they ask for another dump file. I do not have the preview version here so I cannot help. Would you please be so kind as to provide them with another?

**Comment by heku** [comment]
@willemduncan No problem, I'm so busy these days that I didn't have a chance to check its status, thank you for reminder, I'm upgrading the VS to the latest preview version and to see if it has been fixed, if not, I'll upload the dump again.

**Comment by heku** [comment]
Update: The issue seems to be fixed in the VS 15.7 preview 5, after upgrading today, I cannot reproduce it again.

**Comment by codecadwallader** [comment]
Awesome news!

**Comment by willemduncan** [comment]
@heku thanks for checking and updating the support issue! Assuming this ticket can be closed?

**Comment by heku** [comment]
@willemduncan No problem for me, it's better @eliashdezr could have a double confirm this.
