### ISSUE TITLE
Join Line (Ctrl-M, J) Thows an exception in VS2017 15.70 Preview 4.0

### ISSUE THREAD

**Issue by LeoMrozek** [codecadwallader/codemaid#544]
### Environment
Visual Studio 2017 15.7.0 **Preview 4.0**
CodeMaid 10.4
C#

### Description
Code maid throws the following error when attempting to Join Lines. Note, this worked in Visual Studio 2017 15.7.0 Preview 3.0 and works in the current release version 15.6.6

### Steps to recreate
1. Select multiple lines
2. Press Ctrl-M, J
3. Error is thrown in Output Window, lines are not joined

[CodeMaid Diagnostic 10:24:37 AM] JoinLinesCommand.OnExecute invoked
[CodeMaid Handled Exception 10:24:37 AM] CodeMaid Join was stopped: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.TextSelection.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextSelection textSelection, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Integration.Commands.JoinLinesCommand.JoinText(TextSelection textSelection)
   at SteveCadwallader.CodeMaid.Integration.Commands.JoinLinesCommand.<>c__DisplayClass3_0.<OnExecute>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)
[CodeMaid Diagnostic 10:28:52 AM] AboutCommand.OnExecute invoked

### Current behavior
Lines are not joined

### Expected behavior
Lines should be joined

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Similar to #543 it looks like there has been a significant change to the VsRegexFinder class within the Visual Studio API with Preview 4 that is creating a lot of issues.  If you could report this issue to Microsoft, it would be greatly appreciated (quantity of reports matters for their prioritization).
