### ISSUE TITLE
Install Error for VS2017 Professional

### ISSUE THREAD

**Issue by MattJ7th** [codecadwallader/codemaid#573]
### Environment
- Visual Studio version: 2017 Professional
- CodeMaid version: 10.5.119
- Code language: C++

### Description
Failing to install extension log message:
_...
27/07/2018 11:26:43 - Beginning to install extension to Microsoft Visual Studio Professional 2017...
27/07/2018 11:26:43 - Found setup instance eeb6cbf2 but not in launchable state.
27/07/2018 11:26:43 - Install Error : System.InvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)_

Full log attached
[codeMaid_install_log.txt](https://github.com/codecadwallader/codemaid/files/2235474/codeMaid_install_log.txt)

### Current behavior
I also had VS2012 installed, trying to install via the direct download from the CodeMaid website installed for just VS2012. When I tried to install for VS2017 via the extension section in VS it caused the above log error.

When I tried uninstalling VS2012 and running the installer from the website it now says 'The extension manifest is invalid.' and wont run.

Any help would be much appreciated!

**Comment by MattJ7th** [comment]
Its seems this was a more general VS issue and all extensions were behaving in the same way! A re-install of VS2017 has fixed my instance and I'm all good to start using CodeMaid now!

Apologies

**Comment by codecadwallader** [comment]
Interesting, thanks for reporting the issue and following up with the explanation - that may help others that run into it too. :)
