### ISSUE TITLE
Null Exception for  cleanup 

### ISSUE THREAD

**Issue by vinaydhama** [codecadwallader/codemaid#622]
### Environment
- Visual Studio version: [example 2015 Community]
- CodeMaid version: [example 10.6]
- Code language: [example C#]

### Description
Replace this text with a short description and code sample.

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
[CodeMaid Warning 06:02:30 PM] Timed out waiting for code model to be built for 'C:\data\projects\TPE\Rule_Eng\WorkingEnvironment\XMLToClass\XMLToClass.cs'
[CodeMaid Handled Exception 06:02:30 PM] CodeMaid Cleanup for 'XMLToClass.cs' was stopped: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by codecadwallader** [comment]
The error message indicates it was not able to determine the type of a code element, can you provide a minimal sample source file that exhibits the issue?
