### ISSUE TITLE
NullReferenceException on Razor Pages

### ISSUE THREAD

**Issue by gh5692** [codecadwallader/codemaid#653]
### Environment
- Visual Studio version: 2019 Professional 16.1.0
- CodeMaid version: 11.0.183
- Code language: C# (Razor)

### Description
When opening a solution that restores a Razor (.cshtml) page an error banner appears with the message "An exception of type NullReferenceException has been encountered. This may be caused by an extension." Disabling the CodeMaid extension causes the error to go away. This error does not appear if the solution does not open a Razor page on load (i.e. no previously opened pages are reopened).

![image](https://user-images.githubusercontent.com/19535599/58186188-013add00-7c7a-11e9-9167-0d0816508e47.png)

### Steps to recreate
1. Create a new project for C# ASP.NET MVC for framework 4.7.2 accepting the defaults
2. Open all of the .cshtml files
3. Close the project
4. Open the project

### Current behavior
It is throwing an exception

### Expected behavior
Not throwing an exception

**Comment by rocco16v** [comment]
Happens to me too. Here is my VS2019 Log.

[VS2019 - ActivityLog.txt](https://github.com/codecadwallader/codemaid/files/3216813/VS2019.-.ActivityLog.txt)

**Comment by LysakVitaliy** [comment]
the same things here.
in log file says:
System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.DocumentParseCompleteMainThread()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.&lt;DocumentParseComplete&gt;b__45_0()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have been able to reproduce it.

In my testing it seems to be limited to when loading Visual Studio directly from a solution and re-opening those files.  If I load Visual Studio first, then the project the error would not occur.  Similarly opening the files in the first place (i.e. Step 2 in the steps to reproduce above) did not cause the error.

This leads me to think it may be tied to the new asynchronous package loading behavior in VS2019, where CodeMaid is not fully loaded at startup time but is eventually loaded after a moment once the IDE is idle.  Perhaps when CodeMaid is in the process of loading that is causing an unexpected state.

To help with diagnosis, when that banner is shown are there any observed effects?

**Comment by gh5692** [comment]
> To help with diagnosis, when that banner is shown are there any observed effects?

So far, I've noticed you lose IntelliSense and syntax highlighting for .cshtml pages.

**Comment by Camble** [comment]
It might be worth mentioning this has been acknowledged as a bug in VS.
https://developercommunity.visualstudio.com/content/problem/583263/systemnullreferenceexception-after-latest-update.html

**Comment by GearTheWorld** [comment]
It looks like this has been reported since a long time and occurs from multiple sources like searching or just opening a file the first time after starting VS

I'm actually with 16.1.3 and it occurs all the time !

System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.DocumentParseCompleteMainThread()at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.<DocumentParseComplete>b__45_0()at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by GearTheWorld** [comment]
By the way I don't know why Razor since I opened the Web.Config and not a razor page and no razor pages were opened in the solution at that time.
