### ISSUE TITLE
CodeMaid does not work with cast operators in VS 2015

### ISSUE THREAD

**Issue by djanosik** [codecadwallader/codemaid#68]
Hi,

I've found that Spade and Cleanup does not work when the code contains explicit / implicit cast operators.

Can you take a look at this? Does it work in VS 2013?

Thank you!

**Comment by codecadwallader** [comment]
I've confirmed this did work as expected in VS2013.  It does not work with VS2015 CTP 5.  VS2015 CTP 2 was released two days ago, which I'm updating to now.

**Comment by codecadwallader** [comment]
The API call to get the starting position for operator methods is throwing an exception:

[CodeMaid Handled Exception 08:20:28 AM] Unable to build code model for 'C:\codemaid\tests\CodeMaidTestSuite\SpecificIssueTesting\Issue68.cs': System.NotSupportedException: Specified method is not supported.
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.NodeLocator.GetStartPoint(SourceText text, SyntaxNode node, vsCMPart part)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.AbstractNodeLocator.GetStartPoint(SyntaxNode node, Nullable`1 part)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.GetStartPoint(SyntaxNode node, Nullable`1 part)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.<get_StartPoint>b__2()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeElement.get_StartPoint()
   at EnvDTE.CodeElement.get_StartPoint()
   at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.RefreshCachedPositionAndName() in C:\codemaid\src\codemaid\CodeMaid\Model\CodeItems\BaseCodeItemElement.cs:line 87
   at SteveCadwallader.CodeMaid.Model.CodeItems.FactoryCodeItems.CreateCodeItemElement(CodeElement codeElement) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeItems\FactoryCodeItems.cs:line 85
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsRecursively(SetCodeItems codeItems, CodeElement codeElement) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 162
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 149
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsRecursively(SetCodeItems codeItems, CodeElement codeElement) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 170
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItemsFromElements(SetCodeItems codeItems, CodeElements codeElements) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 149
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveCodeItems(SetCodeItems codeItems, FileCodeModel fcm) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 130
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelBuilder.cs:line 76
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel) in C:\codemaid\src\codemaid\CodeMaid\Model\CodeModelManager.cs:line 222

**Comment by codecadwallader** [comment]
I have reported this issue to Microsoft for their help.  Please follow the link and vote the issue up.

https://connect.microsoft.com/VisualStudio/feedback/details/1132030/vs2015-sdk-notsupportedexception-thrown-when-trying-to-access-codefunction2-startpoint-on-explicit-implicit-operator-methods

**Comment by codecadwallader** [comment]
Unfortunately this is still an issue with VS2015 RC, and I have received no feedback from Microsoft on the associated Connect issue.

**Comment by codecadwallader** [comment]
I checked Microsoft Connect again, still no feedback.

**Comment by codecadwallader** [comment]
I've now also reported this on GitHub for Roslyn here: https://github.com/dotnet/roslyn/issues/3908

**Comment by djanosik** [comment]
It seems it's fixed in VS 2015 RTM.

**Comment by codecadwallader** [comment]
Surprising, but confirmed as well!  Thanks for following up.  I'll put comments in the other locations.
