### ISSUE TITLE
CodeMaid throws an uncaught `System.ArgumentNullException`

### ISSUE THREAD

**Issue by kmgallahan** [codecadwallader/codemaid#702]
### Environment
- Visual Studio version: 2019
- CodeMaid version: 11.1.209
- Code language: C#

### Description
It is possible for CodeMaid to throw the following exception, although I have no idea why:

Stack:

```
[CodeMaid Warning 11:44:20 AM] Timed out waiting for code model to be built for 'C:\Project\Class1.cs'
[CodeMaid Handled Exception 11:44:20 AM] CodeMaid Reorganize for 'Class1.cs' was stopped: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.<>c__DisplayClass12_0.<Reorganize>b__0() in C:\projects\codemaid\CodeMaid\Logic\Reorganizing\CodeReorganizationManager.cs:line 117
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction) in C:\projects\codemaid\CodeMaid\Helpers\UndoTransactionHelper.cs:line 55
[CodeMaid Warning 11:44:23 AM] Timed out waiting for code model to be built for 'C:\Project\Class1.cs'
[CodeMaid Handled Exception 11:44:23 AM] CodeMaid Cleanup for 'Class1.cs' was stopped: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document) in C:\projects\codemaid\CodeMaid\Logic\Cleaning\CodeCleanupManager.cs:line 240
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0() in C:\projects\codemaid\CodeMaid\Logic\Cleaning\CodeCleanupManager.cs:line 170
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction) in C:\projects\codemaid\CodeMaid\Helpers\UndoTransactionHelper.cs:line 55
```

### Steps to Reproduce
Really not sure outside of my project as I haven't spent any time investigating, so I'm hoping the stack trace is enough.

### Current behavior
Noticed this exception being thrown, causing cleanup to stop. 

### Expected behavior
Cleanup shouldn't stop, or warning should be displayed rather than uncaught exception. Appears to be caused by:

> Timed out waiting for code model to be built

**Comment by kmgallahan** [comment]
Just noticed this is actually caught, oops. I guess the outcome is an expected condition.
