### ISSUE TITLE
Export solution specific settings: IO file not found issues

### ISSUE THREAD

**Issue by WizX20** [codecadwallader/codemaid#716]
### Environment
- Visual Studio version: 2019 Professional (Version 16.4.6)
- CodeMaid version: 11.1.209
- Code language: C#

### Description
**The export functions fails to export the CodeMaid.config [1 of 2]**
1. Open the CodeMaid options window
2. Switch to solution specific settings
3. Click _Export_
4. Pick a location at the solution root folder
5. Click save
```
[CodeMaid Handled Exception 08:33:42 am] Unable to export Solution-Specific Settings: System.IO.FileNotFoundException: Could not find file 'C:\Repos\MyRepo\SolutionRoot\CodeMaid.config'.
File name: 'C:\Repos\MyRepo\SolutionRoot\CodeMaid.config'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at SteveCadwallader.CodeMaid.UI.Dialogs.Options.OptionsViewModel.OnExportCommandExecuted(Object parameter) in C:\projects\codemaid\CodeMaid\UI\Dialogs\Options\OptionsViewModel.cs:line 232
```

**The export functions fails to export the CodeMaid.config [2 of 2]**
1. Pick a location at the solution root folder
2. At that location, create a new file (via the windows explorer or CLI) called _CodeMaid.config_
1. Open the CodeMaid options window
2. Switch to solution specific settings
3. Click _Export_
5. Select the previously created file
6. Click _YES_ to overwrite the existing file
```
[CodeMaid Handled Exception 08:34:43 am] Unable to read settings.: System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Repos\MyRepo\SolutionRoot\CodeMaid.config) ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at SteveCadwallader.CodeMaid.Helpers.CodeMaidSettingsProvider.GetConfiguration(String path) in C:\projects\codemaid\CodeMaid\Helpers\CodeMaidSettingsProvider.cs:line 107
   at SteveCadwallader.CodeMaid.Helpers.CodeMaidSettingsProvider.ReadSettingsFromFile(String path, String sectionName) in C:\projects\codemaid\CodeMaid\Helpers\CodeMaidSettingsProvider.cs:line 154
[CodeMaid Handled Exception 08:34:51 am] Unable to export Solution-Specific Settings: System.IO.IOException: The process cannot access the file 'C:\Repos\MyRepo\SolutionRoot\CodeMaid.config' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at SteveCadwallader.CodeMaid.UI.Dialogs.Options.OptionsViewModel.OnExportCommandExecuted(Object parameter) in C:\projects\codemaid\CodeMaid\UI\Dialogs\Options\OptionsViewModel.cs:line 232
[CodeMaid Handled Exception 08:37:34 am] Unable to read settings.: System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Repos\MyRepo\SolutionRoot\CodeMaid.config) ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at SteveCadwallader.CodeMaid.Helpers.CodeMaidSettingsProvider.GetConfiguration(String path) in C:\projects\codemaid\CodeMaid\Helpers\CodeMaidSettingsProvider.cs:line 107
   at SteveCadwallader.CodeMaid.Helpers.CodeMaidSettingsProvider.ReadSettingsFromFile(String path, String sectionName) in C:\projects\codemaid\CodeMaid\Helpers\CodeMaidSettingsProvider.cs:line 154
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  It looks like the steps are trying to export the solution-specific settings file right into where it is already located, which could be causing IO conflicts that the file is already open for reading.  Does it work as expected if you export to a separate folder?

**Comment by WizX20** [comment]
Nope. If it's not there it also fails. That's what I demonstrated in the first scenario. Exporting user setting however works fine.

**Comment by codecadwallader** [comment]
Have you made any changes before trying to export the solution-specific settings (i.e. _are_ there any solution-specific settings)?
