### ISSUE TITLE
codemaid keeps reporting slowness and now raised OutOfMemoryException while debugging 

### ISSUE THREAD

**Issue by lachlann562** [codecadwallader/codemaid#749]
### Environment
- Visual Studio version: 2019 Pro (slowness noticed in 2017 Pro as well)
- CodeMaid version: 11.1
- Code language: c# (asp.net core application)

### Description
VS routinely warns that code maid is slowing the system down by X seconds (variable) over time visual studio becomes slow.

Today it threw this error:
[CodeMaid Handled Exception 02:35:38 PM] TryDefault caught an exception on 'System.Func`1[System.Boolean]': System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.EditPoint.FindPattern(String Pattern, Int32 vsFindOptionsValue, EditPoint& EndPoint, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.CodeElementHelper.GetMethodDeclaration(CodeFunction codeFunction) in C:\projects\codemaid\CodeMaid\Helpers\CodeElementHelper.cs:line 169
   at SteveCadwallader.CodeMaid.Helpers.ExplicitInterfaceImplementationHelper.IsExplicitInterfaceImplementation(CodeFunction2 codeFunction) in C:\projects\codemaid\CodeMaid\Helpers\ExplicitInterfaceImplementationHelper.cs:line 51
   at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemMethod.<.ctor>b__6_6() in C:\projects\codemaid\CodeMaid\Model\CodeItems\CodeItemMethod.cs:line 54
   at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.TryDefault[T](Func`1 func) in C:\projects\codemaid\CodeMaid\Model\CodeItems\BaseCodeItemElement.cs:line 139

### Steps to recreate
Unknown

### Current behavior
VS routinely warns that code maid is slowing the system down by X seconds (variable) over time visual studio becomes slow.

### Expected behavior
Visual studio should not slow down when code maid is enabled and should not throw exceptions due to out of memory.

**Comment by codecadwallader** [comment]
Thank you for reporting the issue.  This may be duplicate of #209 if you want to take a look at that to see if there are similarities.
