### ISSUE TITLE
CodeMaid Handled Exception

### ISSUE THREAD

**Issue by T365** [codecadwallader/codemaid#796]
### Environment
Microsoft Visual Studio Community 2019
Version 16.8.5
CodeMaid version: 11.2.231
Visual Micro 2021.106.0

[CodeMaid Handled Exception 12:28:22 ] TryDefault caught an exception on 'System.Func`1[System.Int32]': System.ArgumentException: Value does not fall within the expected range.
   at EnvDTE.EditPoint.GetText(Object PointOrCount)
   at SteveCadwallader.CodeMaid.Helpers.CodeElementHelper.CalculateComplexity(CodeElement element) in C:\projects\codemaid\CodeMaid\Helpers\CodeElementHelper.cs:line 20
   at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemMethod.<.ctor>b__6_2() in C:\projects\codemaid\CodeMaid\Model\CodeItems\CodeItemMethod.cs:line 42
   at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.TryDefault[T](Func`1 func) in C:\projects\codemaid\CodeMaid\Model\CodeItems\BaseCodeItemElement.cs:line 139

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  There are scenarios where CodeMaid is unable to complete an action and it will gracefully log out some additional information such as the call stack above which helps with development/debugging.  In this case it looks like we were unable to complete a complexity calculation for an element due to its contents.  This could be because the code was not valid at the time or it could be because the algorithm isn't handling a specific situation.

I would expect the consequence of this to be very minor, one of the complexity numbers would be blank in the Spade window and it would attempt to re-calculate in the future as normal.

Did you see any negative impacts when this occurred?  If you're continuing to see it and would like to provide a code sample that causes the log to be generated we can look into it.
