### ISSUE TITLE
VS2022: Attempted to edit TextBuffer on the wrong thread

### ISSUE THREAD

**Issue by kfrancis** [codecadwallader/codemaid#849]
### Environment
- Visual Studio version: VS2022
- CodeMaid version: CodeMaid.VS2022.20211014T145200 (see [this](https://github.com/codecadwallader/codemaid/issues/816#issuecomment-943462232))
- Code language: C#

### Description
Solution clean and getting these errors:

```
[CodeMaid Handled Exception 12:49:56 PM] CodeMaid Cleanup for 'ClaimAssertionBackchannelHandler.cs' was stopped: System.InvalidOperationException: Attempted to edit TextBuffer on the wrong thread.
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferBaseEdit..ctor(BaseBuffer baseBuffer)
   at Microsoft.VisualStudio.Text.Implementation.TextBuffer.CreateEdit(EditOptions options, Nullable`1 reiteratedVersionNumber, Object editTag)
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.CreateEdit()
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.ReplaceAll(ITextBuffer textBuffer, IEnumerable`1 replacements) in C:\src\codemaid\CodeMaidShared\Helpers\TextDocumentHelper.cs:line 385
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString) in C:\src\codemaid\CodeMaidShared\Helpers\TextDocumentHelper.cs:line 292
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document) in C:\src\codemaid\CodeMaidShared\Logic\Cleaning\CodeCleanupManager.cs:line 272
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0() in C:\src\codemaid\CodeMaidShared\Logic\Cleaning\CodeCleanupManager.cs:line 170
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction) in C:\src\codemaid\CodeMaidShared\Helpers\UndoTransactionHelper.cs:line 55
```

**Comment by kfrancis** [comment]
Doesn't seem to correspond to what the content is, happens randomly during a large solution clean.

**Comment by codecadwallader** [comment]
Thanks for reporting @kfrancis !  There's an updated build on the main issue if you want to give it a shot and let us know if that helped?

**Comment by kfrancis** [comment]
Perfect!

I do see `Activation was not completed before cleaning began for` warnings, but I don't see the same issue with TextBuffer now.
