### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by gdosborne** [codecadwallader/codemaid#86]
Received the following exception when reorganizing file:
***********************************************
[CodeMaid Handled Exception 10:56:55 AM] Stopped reorganizing 'PropertyTablePanelView.cs': System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.EditPoint.GetText(Object PointOrCount)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.GetTextAndRemoveItem(BaseCodeItem itemToRemove, Int32& cursorOffset)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.RepositionItemAboveBase(BaseCodeItem itemToMove, BaseCodeItem baseItem)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.RecursivelyReorganize(IEnumerable`1 codeItems, ICodeItemParent parent)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.RecursivelyReorganize(IEnumerable`1 codeItems, ICodeItemParent parent)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.RecursivelyReorganize(IEnumerable`1 codeItems, ICodeItemParent parent)
   at SteveCadwallader.CodeMaid.Logic.Reorganizing.CodeReorganizationManager.<>c__DisplayClassd.<Reorganize>b__a()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Can you provide a sample file that exhibits the issue?

**Comment by gdosborne** [comment]
It doesn't always throw exception on this file. For instance, after restarting my development environment, I ran cleanup/reorganization on the same file and it went through perfectly.

Sorry, I know how difficult it is tracking down an issue that only happens intermittently.

**Comment by codecadwallader** [comment]
Ok, thanks for the update.  If you do start encountering the issue again and have a way to reproduce it consistently, please comment here to reopen.
