### ISSUE TITLE
Exception thrown when cleaning a form automatically

### ISSUE THREAD

**Issue by kwhitefoot** [codecadwallader/codemaid#89]
I don't know how often this has happened but I just happened to notice a message in the output window when a VB form was saved.  I have CodeMaid set to clean files automatically on save.
As far as I know it hasn't damaged any files.
For the form in question it happens quite reliably.   Sorry, I can't send the file and anyway it relies on too many other files including user defined controls.

[CodeMaid Handled Exception 10:20:10 AM] Stopped cleaning 'frmUIRoot.vb': System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at EnvDTE.TextDocument.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.RemoveWhitespaceLogic.RemoveEOLWhitespace(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupGeneric(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClassb.<Cleanup>b__9()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
If there's a specific file exhibiting the issue, then there's probably something specific in that file that would be really helpful in diagnosing the issue.  The call stack indicates it is when it is removing end of line whitespace that the error is being thrown.  Does that give you any hints?

**Comment by kwhitefoot** [comment]
I'll try to find out next time it happens.  It didn't seem to happen every time even to the same file.
If I can isolate a particular file I might be able to diff it with previous versions to see what is causing it.
I'll let you know if I find anything.  For now it is working perfectly.

**Comment by codecadwallader** [comment]
Sounds good.  For now I'll close the issue, but when you have more details please simply comment and we'll reopen.
