### ISSUE TITLE
VS 2022 - Clean Up Selected Code gives error

### ISSUE THREAD

**Issue by apsthisdev** [codecadwallader/codemaid#898]
Hi,

The CodeMaid for VS 2022 command **Cleanup Selected Code** on .csproj or on a namespace folder throws an exception.

![image](https://user-images.githubusercontent.com/13166236/149233932-e3fad232-fbaa-4258-835b-7c3417be78eb.png)

I have to manually open each .cs file and then run Cleanup Selected Code individually. This is a pain for project with lot of files.

Earlier version was opening the file and then cleaning it up. 

Here is the log that I get...

[CodeMaid Warning 02:27:55 PM] Activation was not completed before cleaning began for 'test.cs'
[CodeMaid Handled Exception 02:28:01 PM] CodeMaid Cleanup for 'test.cs' was stopped: System.Runtime.InteropServices.COMException (0x8001010E): ReplaceFileHeaderDocumentStart must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.FileHeaderLogic.ReplaceFileHeaderDocumentStart(TextDocument textDocument, String settingsFileHeader) in C:\projects\codemaid\CodeMaidShared\Logic\Cleaning\FileHeaderLogic.cs:line 237
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document) in C:\projects\codemaid\CodeMaidShared\Logic\Cleaning\CodeCleanupManager.cs:line 264
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0() in C:\projects\codemaid\CodeMaidShared\Logic\Cleaning\CodeCleanupManager.cs:line 170
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction) in C:\projects\codemaid\CodeMaidShared\Helpers\UndoTransactionHelper.cs:line 55

**Comment by josercsouza** [comment]
Hi..
This error happen when I try the same command (VS 2019 & 2022). Using from Solution Explorer, none error.

![image](https://user-images.githubusercontent.com/31997645/149949801-081f1b6a-923c-44a3-9e7d-9244c6389443.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Based on the call stack it looks like it is specifically the usage of a file header that is causing an issue.  Out of curiosity if you remove the file header does it work as expected?
